"""
v2.1 Phase 9 -- the tables the team's decisions are asked with (execution prompt, "Decisions"), generated from their
files so that no number in the question is typed (rules 15, 19).

    python -u -m tools.phase9.e9_decision_tables

Reads e9_0/{throughput.csv, wallclock.csv}, e9_3/{refdist_fresh.json, refdist_boot.csv, rule_check.json} and writes
e9_0/decision_tables.md.
"""
from __future__ import annotations

import json
import os
import sys

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:  # pragma: no cover
    pass
GEN =os.path.join(ROOT, "docs", "env_v2", "generated", "v2_1")
E0, E3 = os.path.join(GEN, "e9_0"), os.path.join(GEN, "e9_3")
DESIGNS_SHOWN = ("headline_12cells", "sweep_tierA", "tierA_shape")
SEEDS_SHOWN = (47, 93)
MS_SHOWN = (3, 4, 5, 6, 8, 10, 12, 14)


def _md(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(str(c) for c in cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        out.append("| " + " | ".join(str(r[c]) for c in cols) + " |")
    return "\n".join(out)


def throughput_md() -> str:
    t = pd.read_csv(os.path.join(E0, "throughput.csv"))
    t = t[t.config_tag != "untagged"]
    keep = []
    for (m, tag), g in t.groupby(["model", "config_tag"]):
        keep.append(g[g.kind == "batch"].iloc[0] if "batch" in set(g.kind) else g[g.kind == "smoke"].iloc[0])
    k = pd.DataFrame(keep).sort_values("runs_per_stream_hour", ascending=False)
    k = pd.DataFrame({"model · configuration": k.model + " · " +k.config_tag, "timed by": k.kind + " (n = " + k.n_runs.astype(str) + ")",
                      "s / run": k.mean_s_per_run.round(0).astype(int), "s / call": k.s_per_call.round(2),
                      "reasoning tokens / call": k.reasoning_tokens_per_call.round(0).astype(int),
                      "runs per stream-hour": k.runs_per_stream_hour.round(2),
                      "LLM errors / fallbacks": k.llm_errors.astype(str) + " / " + k.fallbacks.astype(str)})
    return _md(k)


def wallclock_md(streams: int) -> str:
    w = pd.read_csv(os.path.join(E0, "wallclock.csv"))
    w = w[(w.streams == streams) & w.design.isin(DESIGNS_SHOWN) & w.seeds_per_cell.isin(SEEDS_SHOWN)]
    w["cell"] = w.apply(lambda r: f"{r['days']:.1f}" + (f" ({r['hours_smoke_ratio_adjusted'] / 24:.1f})" if r["rate_source"] == "smoke" else ""), axis=1)
    piv = w.pivot_table(index=["model", "config_tag", "rate_source"], columns=["design", "seeds_per_cell"], values="cell", aggfunc="first")
    piv.columns = [f"{d} @ {int(s)} seeds ({int(w[(w.design == d) & (w.seeds_per_cell == s)].runs_per_model.iloc[0]):,} runs)" for d, s in piv.columns]
    piv = piv.reset_index()
    piv.insert(0, "model · configuration (rate)", piv.model + " · " +piv.config_tag + " (" + piv.rate_source + ")")
    return _md(piv.drop(columns=["model", "config_tag", "rate_source"]))


def refdist_md() -> str:
    d = json.load(open(os.path.join(E3, "refdist_fresh.json"), encoding="utf-8"))
    rc = json.load(open(os.path.join(E3, "rule_check.json"), encoding="utf-8")) if os.path.exists(os.path.join(E3, "rule_check.json")) else None
    reg, r5 = d["recommendation_registered_candidates"], d["recommendation_with_R5"]
    rows = []
    for M in MS_SHOWN:
        a, b = reg[str(M)], r5[str(M)]
        rows.append({"models": M, **{f"{c} conditions breaking (of 48)": b["n_conditions_breaking"][c] for c in ("R1", "R2", "R4", "R5")},
                     "R3 (of 8)": ("holds" if a["holds_size"].get("R3") else "fails") if "R3" in a["holds_size"] else "not run",
                     "registered rule": a["recommended"] or "none", "rule with R5": b["recommended"] or "none"})
    txt = _md(pd.DataFrame(rows))
    if rc:
        txt += (f"\n\nAn exactly sized test breaks this rule at a given M with probability "
                f"{rc['exactly_sized_test_fails_rule_per_M_analytic']:.2f} (48 conditions, both alphas; "
                f"`e9_3/rule_check.json`).")
    return txt


def power_md() -> str:
    s = pd.read_csv(os.path.join(E3, "refdist_fresh.csv"))
    s = s[(s.beta > 0) & (~s.hetero) & (~s.shared) & s.S.isin(SEEDS_SHOWN) & s.M.isin(MS_SHOWN)]
    s["tau"] = s.tau_label.map({"0": "0", "half_limit": "½ Flash limit", "limit": "Flash limit", "p8_sma0.03": "√2 × 0.03"})
    piv = s.pivot_table(index=["S", "tau"], columns="M", values="R5_reject_prime").round(2).reset_index()
    piv.columns = [str(c) for c in piv.columns]
    return _md(piv)


def main(argv=None):
    doc = ["# Phase 9 — the tables the roster, design and reference-distribution questions are asked with",
           "", "*Generated by `tools/phase9/e9_decision_tables.py` from the files named under each table.*", "",
           "## Throughput per configuration (`e9_0/throughput.csv`)", "", throughput_md(), "",
           "## Wall-clock in days per model at 15 concurrent calls (`e9_0/wallclock.csv`)",
           "", "Every model runs at once, so a roster's wall-clock is its slowest member's. A smoke-timed rate is a lower "
           "bound; in brackets it is scaled by the largest measured batch / smoke ratio.", "", wallclock_md(15), "",
           "## The same at 10 concurrent calls", "", wallclock_md(10), "",
           "## Reference distribution for a model-level contrast: size (`e9_3/refdist_fresh.json`, `refdist_boot.csv`)", "",
           refdist_md(), "",
           "## R5's power at α′ = 0.05 / 36 to detect Δ = 0.05, model-specific reading, equal heterogeneity (`e9_3/refdist_fresh.csv`)",
           "", power_md(), ""]
    out = os.path.join(E0, "decision_tables.md")
    open(out, "w", encoding="utf-8", newline="\n").write("\n".join(doc))
    print("\n".join(doc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
