"""Generate datasets/<need>/README.md from the files actually on disk.

Counts, ranges and file lists are read from the data, so re-running the download
and then this script keeps every README truthful.
"""
from __future__ import annotations

import sys
import warnings
from datetime import date
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from common import DATASETS  # noqa: E402

warnings.filterwarnings("ignore")
TODAY = date.today().isoformat()
HDR = "<!-- generated by tools/e1_0_data/write_readmes.py; do not edit by hand -->\n\n"


def listing(folder: Path, skip: set[str] = frozenset()) -> str:
    lines = ["| file | size | rows |", "|---|---:|---:|"]
    for p in sorted(folder.rglob("*")):
        if p.is_dir() or p.name == "README.md" or p.name in skip:
            continue
        rel = p.relative_to(folder).as_posix()
        n = ""
        try:
            if p.suffix == ".csv":
                n = "{:,}".format(sum(1 for _ in open(p, encoding="utf-8", errors="ignore")) - 1)
            elif p.suffix == ".parquet":
                n = "{:,}".format(len(pd.read_parquet(p)))
        except Exception:
            n = "?"
        lines.append("| `%s` | %s | %s |" % (rel, sizeof(p.stat().st_size), n))
    if len(lines) > 30:
        lines = lines[:30] + ["| ... (%d more files) | | |" % (len(lines) - 30)]
    return "\n".join(lines)


def sizeof(b: int) -> str:
    for u in ["B", "KB", "MB", "GB"]:
        if b < 1024 or u == "GB":
            return "%.0f %s" % (b, u) if u == "B" else "%.1f %s" % (b, u)
        b /= 1024.0
    return str(b)


def w(folder: Path, text: str) -> None:
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "README.md").write_text(HDR + text.strip() + "\n", encoding="utf-8")
    print("wrote", (folder / "README.md").relative_to(DATASETS.parent))


def write_index() -> None:
    """Top-level map of the panel, with live counts read off disk."""
    def nfiles(sub, pat="*"):
        d = DATASETS / sub
        return sum(1 for x in d.rglob(pat) if x.is_file()) if d.exists() else 0

    def rows(path, col=None):
        p = DATASETS / path
        if not p.exists():
            return "-"
        try:
            if p.suffix == ".csv":
                n = sum(1 for _ in open(p, encoding="utf-8", errors="ignore")) - 1
            else:
                n = len(pd.read_parquet(p))
            return "{:,}".format(n)
        except Exception:
            return "?"

    def okcount(path):
        p = DATASETS / path
        if not p.exists():
            return "-"
        try:
            d = pd.read_csv(p).fillna("")
            return "{:,}".format(int((d.status == "ok").sum()))
        except Exception:
            return "?"

    total = sum(1 for x in DATASETS.rglob("*") if x.is_file())
    w(DATASETS, """
# E1.0 shared data panel

Real-market data backing the FinPersona-Bench v2.1 environment rebuild
(`docs/env_v2/v2_1/V2_1_IMPROVEMENT_PLAN.md`, step E1.0). The plan's rule is that
every generator parameter is **fitted or tested on data**, not stipulated; each
folder below supplies one input to that.

**Not committed to git** (`datasets/` is in `.gitignore`) - several sources
forbid redistribution. Everything here is re-downloadable: see
`tools/e1_0_data/` and section 12 of the report.

**Full write-up:** `docs/env_v2/v2_1/E1_0_DATA_REPORT.md`
**This map:** %d files. Every folder has its own `README.md` with source, URL,
licence, schema, row counts and caveats.

| # | folder | what it is | key numbers | used for |
|---|---|---|---|---|
| 1 | `01_prices/` | daily OHLCV, historical S&P 500 names (Yahoo) | **%s** tickers | fits sigma_V, s_x, h; GARCH; crash/run-up episodes |
| 2 | `02_constituents/` | index membership with add/remove dates | **%s**-name universe | defines the #1 universe; survivorship count for D1/REG-15 |
| 3 | `03_fundamentals/` | quarterly EPS, DPS, filing dates (SEC EDGAR) | **%s** filers | second estimator of (sigma_V, s_x, h); jump placement; EPS/DPS fields |
| 4 | `04_shiller/` | monthly index valuation, 1871-> (Shiller) | **%s** months | fits mu_V (drift); long-run P/E and payout |
| 5 | `05_implied_vol/` | CBOE + Yahoo + FRED volatility indices | **%s** files | the IV field the persona reads; IV-vs-realised-vol |
| 6 | `06_sentiment/` | daily / weekly / monthly sentiment | 3 frequencies | the sentiment field; its persistence and return correlation |
| 7 | `07_factors_valuation/` | Fama-French factors, risk-free, Damodaran | 11 files | risk-free rate; industry P/E cross-check |
| 8 | `08_price_crosscheck/` | independent daily prices (Nasdaq) | **%s** tickers | audits #1; caught the ticker-reuse defect |

## Cross-cutting files (`_manifests/`)

| file | what it holds |
|---|---|
| `survivorship_accounting.csv` | per-ticker: in index when, retrieved or not, full history or not - the REG-15 input |
| `ticker_reuse_screen.csv` | per-ticker reuse flags; **read this before using the delisted tail** |
| `source_agreement.csv` | need #1 vs need #8, per ticker, on returns and levels |
| `quality_prices.csv` | per-ticker gaps, duplicates, non-positive prices, >50%% returns, zero volume |
| `quality_other.csv` | the same checks for every non-price series |
| `reachability_probe.csv` | which hosts this machine can reach, and how they fail |
| `attempts_*.json` | every network attempt with a UTC timestamp, outcome and detail - including refusals |

## Three things to know before using this

1. **Ticker reuse.** Yahoo serves whoever holds a symbol today. 86 of 673 series
   belong to a different company than the S&P 500 constituent of that name
   (`FB` is now an ETF; `GP` is GreenPower Motor, not Georgia-Pacific). Check
   `_manifests/ticker_reuse_screen.csv` first. Nothing was excluded - Phase 1
   sets that rule.
2. **Survivorship.** Of 342 names that left the index in 2000-2024, only **16**
   have a clean price series. The delisted tail - the crashes Phases 3, 4 and 6
   want most - is largely absent, and no free source fixes it.
3. **Nothing was cleaned.** Files are as served; anomalies are reported, not
   repaired.
""" % (total, okcount("01_prices/retrieval_log.csv"), rows("02_constituents/universe_2000_2024.csv"),
       okcount("03_fundamentals/retrieval_log.csv"), rows("04_shiller/shiller_monthly.csv"),
       nfiles("05_implied_vol", "*.csv") + nfiles("05_implied_vol", "*.parquet"),
       okcount("08_price_crosscheck/retrieval_log.csv")))


def main() -> int:
    # ---------------------------------------------------------------- #1 prices
    f = DATASETS / "01_prices"
    log = pd.read_csv(f / "retrieval_log.csv").fillna("") if (f / "retrieval_log.csv").exists() else pd.DataFrame()
    ok = log[log.status == "ok"] if len(log) else log
    scr = DATASETS / "_manifests" / "ticker_reuse_screen.csv"
    scr_txt = ""
    if scr.exists():
        s = pd.read_csv(scr).fillna("")
        nstart = int(s["flags"].astype(str).str.contains("starts_").sum())
        scr_txt = ("\n**Ticker-reuse screen.** `_manifests/ticker_reuse_screen.csv` flags "
                   "**%d of %d retrieved tickers (%.1f %%)** whose Yahoo series belongs to a "
                   "*different* company that later took the symbol. Verified: CPWR "
                   "(Compuware -> Ocean Thermal Energy), COMS (3Com -> COMSovereign), "
                   "EP (El Paso -> Empire Petroleum), CVG (-> a mutual fund), FB "
                   "(Facebook -> a ProShares ETF), S (Sears -> SentinelOne), LU "
                   "(Lucent -> Lufax), GP (Georgia-Pacific -> GreenPower Motor).\n\n"
                   "Five criteria: `quoteType != EQUITY`, OTC/pink venue, max daily return "
                   "> 100 %%, zero volume on > 25 %% of days, and "
                   "**`starts_<N>d_after_index_exit`** - the series begins more than 180 days "
                   "after the name left the index, which a continuous history of one company "
                   "cannot do. That test alone flags **%d** names and is the decisive one; a "
                   "metadata-only screen missed 44 of them. Nothing was deleted; Phase 1 "
                   "decides what to exclude.\n"
                   % ((s.n_flags > 0).sum(), len(s), 100 * (s.n_flags > 0).mean(), nstart))
    w(f, """
# Need #1 - Daily prices and volume, historical S&P 500 names

| field | value |
|---|---|
| Source | Yahoo Finance, via `yfinance` %s |
| URL | https://finance.yahoo.com (undocumented JSON endpoints used by yfinance) |
| Date fetched | %s |
| Licence / terms | Yahoo Finance Terms of Service: personal, non-commercial use. No redistribution. Data are **not** committed to git (`datasets/` is git-ignored). |
| Rate limit | Not published. Downloaded in batches of 40 symbols, 4 threads, 2 s pause between batches. |
| Format | One Parquet file per ticker in `daily/` |
| Date range requested | 2000-01-01 to 2026-01-01 |
| Tickers attempted | %d (the need #2 universe) |
| Tickers retrieved | %d |

## Schema (`daily/<TICKER>.parquet`)

`Date` (datetime64, tz-naive), `Open`, `High`, `Low`, `Close`, `Adj Close` (float),
`Volume` (int), `Dividends`, `Stock Splits` (float). Written exactly as served:
no cleaning, no filling, no adjustment beyond Yahoo's own `Adj Close`.

## Retrieval log

`retrieval_log.csv` - one row per attempted ticker: `ticker`, `yahoo_symbol`,
`status` (`ok` / `no_data` / `batch_error`), `n_rows`, `first`, `last`, `detail`.
Names that returned nothing are the survivorship measurement REG-15 asks for and
are listed, not dropped.
%s
## Known limitations

1. **Survivorship.** Only symbols Yahoo still resolves return data. Names delisted
   before Yahoo's coverage (Enron, Lehman, WorldCom, Compaq, AMR) return nothing.
   Of the 342 names that left the index in 2000-2024, 84 returned data but only
   **16 survive the reuse screen** - genuine delisted coverage is about **4.7 %%**,
   not the 24.6 %% the raw retrieval rate suggests.
2. **Ticker reuse.** See the screen above.
3. **Cross-checked.** Need #8 (`datasets/08_price_crosscheck/`) provides an
   independent Nasdaq series for ~2016-2025. Yahoo and Nasdaq agree on daily
   returns to a median per-ticker correlation of 1.000000, so the price data
   itself is sound; the reuse problem is a symbol-mapping issue, not a price one.

## Files

%s
""" % (_yfver(), TODAY, len(log), len(ok), scr_txt, listing(f, skip={"retrieval_log.csv"})))

    # --------------------------------------------------------- #2 constituents
    f = DATASETS / "02_constituents"
    uni = pd.read_csv(f / "universe_2000_2024.csv") if (f / "universe_2000_2024.csv").exists() else pd.DataFrame()
    w(f, """
# Need #2 - Historical S&P 500 constituents with add/remove dates

The plan's original candidate (the Wikipedia "Selected changes to the list of
S&P 500 components" table) was **removed from the live article in Aug 2025**.
It is recovered here from the last revision that still carried it, and
cross-checked against two independent MIT-licensed datasets.

| # | Source | URL | Licence | Fetched | Coverage |
|---|---|---|---|---|---|
| A | `fja05680/sp500` | https://github.com/fja05680/sp500 | MIT | %s | point-in-time components, 1996-01-02 -> 2026-06-30 |
| B | `hanshof/sp500_constituents` | https://github.com/hanshof/sp500_constituents | MIT | %s | daily point-in-time components, 1996-01-02 -> 2025-08-23 |
| C | Wikipedia, revision 1295035732 (2025-06-11) | https://en.wikipedia.org/w/index.php?oldid=1295035732 | CC BY-SA 4.0 | %s | add/remove table 1994-09-30 -> 2025-05-19; components table with CIKs |

## Derived file: `universe_2000_2024.csv`

Every ticker in the index at **any** time between 2000-01-01 and 2024-12-31:
**%d distinct tickers**.

| column | meaning |
|---|---|
| `ticker` | bare symbol (fja05680's `-YYYYMM` exit suffix stripped) |
| `first_seen`, `last_seen` | first/last date the ticker appears in any source, clipped to the window |
| `exit_hint` | `YYYY-MM` when fja05680 marks the symbol as having left the index (blank if it had not by 2024-12-31) |
| `n_sources`, `sources` | how many of the five source views contain it, and which |

## Cross-source agreement

Jaccard overlap of the membership sets of A and B, after stripping A's exit
suffix: 0.943 (2000-01-03), 0.918 (2005), 0.884 (2010), 0.924 (2015),
0.984 (2020), 0.996 (2024-12-31). The residual disagreement is concentrated in
the early 2000s and in share-class spellings.

## Caveat

None of these is the official S&P Dow Jones Indices membership file, which is
licensed. They are community reconstructions, mostly from Wikipedia history, so
they inherit its errors. They agree closely with each other, which bounds but
does not eliminate that risk.

## Files

%s
""" % (TODAY, TODAY, TODAY, len(uni), listing(f)))

    # -------------------------------------------------------- #3 fundamentals
    f = DATASETS / "03_fundamentals"
    flog = pd.read_csv(f / "retrieval_log.csv").fillna("") if (f / "retrieval_log.csv").exists() else pd.DataFrame()
    fok = flog[flog.status == "ok"] if len(flog) else flog
    w(f, """
# Need #3 - Quarterly EPS, DPS, period ends and filing dates

| field | value |
|---|---|
| Source | SEC EDGAR XBRL **company facts** API |
| URL | `https://data.sec.gov/api/xbrl/companyfacts/CIK##########.json` |
| Date fetched | %s |
| Licence | US federal government work, public domain. SEC asks for a declared User-Agent and <= 10 requests/s; this run declares one and stays near 3/s. |
| Format | one Parquet file per ticker in `by_ticker/` |
| Tickers attempted | %d |
| Tickers with facts | %d |

## Ticker -> CIK resolution

Three public files, in this order (the winner is recorded per row in
`retrieval_log.csv:cik_source`):

1. `https://www.sec.gov/include/ticker.txt` - current registrants.
2. The CIK column of the archived Wikipedia constituents table (need #2).
3. `https://www.sec.gov/Archives/edgar/cik-lookup-data.txt` - SEC's historical
   company-name -> CIK list, matched on an **exactly normalised** company name
   taken from the Wikipedia changes table. This is what recovers delisted
   filers; it resolved 155 of 184 otherwise-unmatched names.

`https://www.sec.gov/files/company_tickers.json` returned HTTP 403
("Request Rate Threshold Exceeded") on every attempt from this machine and was
not used; `ticker.txt` on the same host served normally.

## Schema (`by_ticker/<TICKER>.parquet`)

`ticker`, `cik`, `concept`, `unit`, `start`, `end`, `val`, `fy`, `fp`, `form`,
`filed`, `frame`, `accn` - one row per reported fact. `end` is the period end,
`filed` the filing date, `form` the filing type (10-Q / 10-K / 8-K ...).

Concepts kept (`us-gaap`): `EarningsPerShareBasic`, `EarningsPerShareDiluted`,
`CommonStockDividendsPerShareDeclared`, `CommonStockDividendsPerShareCashPaid`,
plus `NetIncomeLoss` and `StockholdersEquity` (same JSON, no extra request;
they support the book-to-market and profitability references in plan 5.1).

The ~3.8 MB raw JSON per filer is **not** stored; only the extracted rows are.

## Known limitations

1. XBRL coverage starts around **2009** - earlier quarters do not exist here.
2. `filed` is the filing date, not the 8-K earnings-announcement date; the plan
   (Section 3) notes these differ by up to two weeks.
3. Tag usage varies across filers; no harmonisation was applied.

## Files

%s
""" % (TODAY, len(flog), len(fok), listing(f, skip={"retrieval_log.csv", "sec_ticker_cik.txt"})))

    # ------------------------------------------------------------- #4 Shiller
    f = DATASETS / "04_shiller"
    w(f, """
# Need #4 - Long-run index valuation history (Shiller)

| field | value |
|---|---|
| Source | Robert J. Shiller, "Online Data", current workbook |
| URL | https://shillerdata.com/ -> `ie_data.xls` |
| Date fetched | %s |
| Licence | Public academic dataset, free to use with attribution to Shiller. Not committed to git. |
| Format | `ie_data.xls` (as served) and `shiller_monthly.csv` (sheet `Data`, parsed) |
| Rows | 1,868 monthly observations |
| Range | 1871.01 -> 2026.08 |

The Yale copy of this file ends 2023.09; the shillerdata.com copy used here is
current, as the plan's verification log records.

## Schema note

The `Date` column is a **fractional year**, not a date: `1871.01` = Jan 1871,
`2026.10` = Oct 2026. Parse as `YYYY.MM`. Columns include S&P Comp. price,
Dividend, Earnings, CPI, Long Interest Rate, real series, and CAPE.

## Cross-check

`datahub_sp500_shiller_crosscheck.csv` (https://github.com/datasets/s-and-p-500,
PDDL) is an independent transcription of the **same** Shiller series. It checks
the parse, not the measurement - it is not a second source.

## Files

%s
""" % (TODAY, listing(f)))

    # -------------------------------------------------------- #5 implied vol
    f = DATASETS / "05_implied_vol"
    ivlog = pd.read_csv(f / "retrieval_log.csv") if (f / "retrieval_log.csv").exists() else pd.DataFrame()
    w(f, """
# Need #5 - Implied volatility

**Fully satisfied**, including the five CBOE **single-stock** VIX indices the
plan names (see `cboe/` below). Three sources are held: CBOE (authoritative),
Yahoo (independent) and FRED (a verbatim mirror of CBOE).

Fetched %s. Start with **`cboe/`** - it is the reference set; the Yahoo files
below are kept as the independent cross-check.

## Yahoo Finance volatility indices (via `yfinance`)

Licence: Yahoo ToS, personal/non-commercial. Underlying indices are CBOE's.

| series | meaning | rows | range |
|---|---|---:|---|
| `VIX.csv` | CBOE Volatility Index (S&P 500, 30-day) | 9,233 | 1990-01-02 -> 2026-08-28 |
| `VXN.csv` | CBOE Nasdaq-100 Volatility Index | 6,437 | 2001-01-23 -> 2026-08-27 |
| `VVIX.csv` | volatility of VIX | 4,936 | 2007-01-03 -> 2026-08-28 |
| `OVX.csv` | CBOE Crude Oil ETF Volatility Index | 4,856 | 2007-05-10 -> 2026-08-27 |
| `GVZ.csv` | CBOE Gold ETF Volatility Index | 4,588 | 2008-06-03 -> 2026-08-27 |

Schema: `Date`, `Open`, `High`, `Low`, `Close`, `Volume`, `Dividends`,
`Stock Splits`. Use `Close` as the index level.

## Also here: FRED series (`fred/`)

Public no-key CSV endpoint (`fredgraph.csv`), US public domain. **No API key used.**
FRED is intermittent from this network - it timed out on every request early on
29 Aug 2026 and served normally about an hour later; re-run to fill gaps.

| file | series | rows | range |
|---|---|---:|---|
| `fred/VIXCLS.csv` | CBOE VIX (official) | 9,563 | 1990-01-02 -> 2026-08-27 |
| `fred/VXNCLS.csv` | CBOE Nasdaq-100 volatility | 6,671 | 2001-02-02 -> 2026-08-27 |
| `fred/VXOCLS.csv` | CBOE S&P 100 volatility (old VIX method) | 9,321 | **1986-01-02** -> 2021-09-23 |
| `fred/DGS3MO.csv`, `fred/DGS10.csv` | Treasury constant maturity 3m / 10y | 11,738 / 16,868 | 1981-> / 1962-> |
| `fred/DFF.csv` | effective federal funds rate | 26,356 | 1954-07-01 -> 2026-08-27 |
| `fred/SP500.csv` | S&P 500 index level | 2,610 | 2016-08-29 -> 2026-08-28 |

Schema: `observation_date`, `<SERIES_ID>`. Missing days are `.` in FRED's CSV.

**Cross-check.** Yahoo `^VIX` vs FRED `VIXCLS` over 9,229 shared trading days:
99.87 %% identical to within 0.01, correlation 0.99999242, mean absolute
difference 0.00057. Only 9 days differ by more than 0.05 (half-days/holidays).

## CBOE (`cboe/`) - obtained on the second pass

`cboe.com` was DNS-filter-blocked on the first pass; the filter was later lifted
and the files served normally. `robots.txt` disallows only `/book/` and
`/*market_statistics/volume_reports/`, so this path is permitted.

Source: `https://cdn.cboe.com/api/global/us_indices/daily_prices/<SYM>_History.csv`
Schema: `DATE` (from MM/DD/YYYY), `OPEN`, `HIGH`, `LOW`, `CLOSE`.
Stored as served (`*_History.csv`) plus a parsed `*.parquet` each.

**The five single-stock VIX indices** (what plan section 5.2 asked for), each
3,929 rows, 2011-01-07 -> 2026-08-28: `VXAPL` (Apple), `VXAZN` (Amazon),
`VXGOG` (Alphabet), `VXGS` (Goldman Sachs), `VXIBM` (IBM).

Index: `VIX` (9,261 rows, 1990-01-02->), `VXN`, `VXO` (1993->2021), `VXD`,
`RVX`, `VVIX` (2006->), `SKEW` (1990->).
Term structure: `VIX9D`, `VIX3M`, `VIX6M` (2008->).
ETF / sector: `VXEEM`, `VXEWZ`, `VXSLV`, `VXGDX`, `VXXLE`, `VXTLT` (2004->),
`GVZ`, `OVX`, `VPD`, `VPN`.

25 of 25 requested files retrieved; see `cboe/retrieval_log.csv`.

## Three-way validation

Over the 9,228 days CBOE, Yahoo and FRED all cover:

| pair | identical to 0.01 | max diff | correlation |
|---|---:|---:|---|
| **CBOE vs FRED** | **100.00 %%** | **0.000** | **1.00000000** |
| CBOE vs Yahoo | 99.87 %% | 2.610 | 0.99999242 |

**FRED republishes CBOE verbatim** - it is a mirror, not an independent
measurement. Use CBOE as the reference series; Yahoo is independent and agrees
to within 0.01 on 99.87 %% of days (the 9 exceptions are half-days/holidays).

## Files

%s
""" % (TODAY, listing(f)))

    # --------------------------------------------------------- #6 sentiment
    f = DATASETS / "06_sentiment"
    w(f, """
# Need #6 - Sentiment series

**Satisfied at all three frequencies** - daily, weekly and monthly.

| frequency | series | source | licence | rows | range | file |
|---|---|---|---|---:|---|---|
| **Daily** | news sentiment | Federal Reserve Bank of San Francisco (Shapiro, Sudhof & Wilson 2022, *J. Econometrics* 228) | Public, cite the paper | 17,018 | 1980-01-01 -> 2026-08-23 | `sf_fed_news_sentiment.csv` |
| **Weekly** | investor survey | **AAII** (manual download, see below) | **AAII copyright; do not republish** | **2,041** | **1987-06-26 -> 2026-08-27** | `aaii_sentiment_weekly.csv` |
| **Monthly** | investor sentiment | Baker & Wurgler, NYU Stern | Public academic, cite Baker & Wurgler (2006) | 792 | 1958-01 -> 2023-12 | `bw_SENTIMENT_DATA.csv` |
| Monthly/annual | v23 workbook | Baker & Wurgler | as above | 648 / 105 | see file | `bw_Investor_Sentiment_POST *.csv` |

Fetched %s.

* SF Fed: `date`, `News Sentiment`. The workbook's first sheet is
  `Methodology`; the series is on the sheet named `Data`.
* Baker-Wurgler `bw_SENTIMENT_DATA.csv`: `yearmo` (YYYYMM), `SENT`,
  `SENT_ORTH`, and the component series (`pdnd`, `ripo`, `nipo`, `cefd`, `s`).
  The index ends **Dec 2023**, as the plan's verification log records.

## AAII weekly survey - obtained by MANUAL download

`www.aaii.com/robots.txt` carries `Disallow: /files/*` for `User-agent: *`, so a
script must not fetch `/files/surveys/sentiment.xls` even though the file is
served plainly. `robots.txt` binds automated clients, not people: the file was
downloaded in a browser to `sentiment.xls` and parsed by
`tools/e1_0_data/ingest_manual.py` into `aaii_sentiment_weekly.csv`.

(The HTML page `/sentimentsurvey/sent_results` returns a JavaScript bot-challenge
and is not a data route.)

**`aaii_sentiment_weekly.csv`** - sheet `SENTIMENT`, **2,041 rows,
1987-06-26 -> 2026-08-27**:

| column | meaning |
|---|---|
| `Date` | survey week ending |
| `Bullish`, `Neutral`, `Bearish` | response shares as **fractions** (0-1), not percentages |
| `Total` | the three shares summed |
| `Mov Avg` | AAII's 8-week moving average of `Bullish` |
| `Spread` | `Bullish - Bearish` |
| `Average`, `+St. Dev.`, `- St. Dev.` | long-run summary constants, repeated on every row |
| `High`, `Low`, `Close` | S&P 500 levels AAII bundles alongside |

Quality: 0 duplicate dates; median spacing exactly 7 days; one 21-day gap at
1987-07-17. `Bullish + Neutral + Bearish` sums to 1.0 within 0.005 on all 2,038
populated rows. The first two rows carry no survey values, so the usable series
starts 1987-07-24. The last two rows repeat identical `High`/`Low`/`Close` - a
stale index quote in AAII's own file, left uncorrected.

**Licence: AAII holds copyright.** Free to download and use; do **not** republish.
Like the Yahoo, CBOE and Nasdaq data it stays inside the git-ignored `datasets/`
tree.

To refresh it, download the file again by hand and re-run
`python tools/e1_0_data/ingest_manual.py`.

## Files

%s
""" % (TODAY, listing(f)))

    # ------------------------------------------------- #7 factors / valuation
    f = DATASETS / "07_factors_valuation"
    w(f, """
# Need #7 - Factor, risk-free and industry valuation series

| source | URL | licence | fetched |
|---|---|---|---|
| Kenneth R. French Data Library | https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ | Free for research; cite Fama & French | %s |
| Aswath Damodaran datasets | https://pages.stern.nyu.edu/~adamodar/pc/datasets/ | Free to use with attribution | %s |

## French library (ZIPs, as served)

* `F-F_Research_Data_Factors_daily_CSV.zip` - Mkt-RF, SMB, HML **and RF**
  (the daily risk-free series the plan needs).
* `F-F_Research_Data_5_Factors_2x3_daily_CSV.zip` - five-factor daily.
* `F-F_Momentum_Factor_daily_CSV.zip` - momentum daily.
* `F-F_Research_Data_Factors_CSV.zip` - monthly three-factor.
* `49_Industry_Portfolios_daily_CSV.zip` - 49 industry portfolios, daily.

Each ZIP holds a CSV with several header lines before the data block and a
second block of annual figures after it - read with an explicit `skiprows` and
stop at the blank line. Values are in **percent**.

## Damodaran (Excel, as served, January 2026 update)

`pedata.xls` (industry P/E), `divfund.xls` (payout and dividend fundamentals),
`histretSP.xls` (historical index/bond/bill returns), `betas.xls`,
`wacc.xls`, `pbvdata.xls` (price-to-book by industry).

Each workbook has two sheets: `Variables & FAQ` and **`Industry Averages`**
(~104 industry rows) - the latter holds the figures. These are the industry P/E
and payout cross-checks of plan Section 3.

## Files

%s
""" % (TODAY, TODAY, listing(f)))

    # ------------------------------------------------ #8 cross-check (obtained)
    f = DATASETS / "08_price_crosscheck"
    xlog = pd.read_csv(f / "retrieval_log.csv").fillna("") if (f / "retrieval_log.csv").exists() else pd.DataFrame()
    xok = xlog[xlog.status == "ok"] if len(xlog) else xlog
    w(f, """
# Need #8 - Second daily price source (cross-check for need #1)

| field | value |
|---|---|
| Source | Nasdaq public historical-quote endpoint |
| URL | `https://api.nasdaq.com/api/quote/<SYM>/historical` |
| Date fetched | %s |
| Licence / access | Public JSON endpoint, **no account and no API key**. Nasdaq site terms cover reference/research use; not redistributed (`datasets/` is git-ignored). |
| Rate limit | Not published; run at 0.5 s between requests |
| Depth | ~2,349 trading days per ticker, about 2016-08-29 -> 2025-12-31 |
| Tickers attempted | %d |
| Tickers retrieved | %d |

This host was DNS-filter-blocked on the first pass; the filter was later lifted.

## Schema (`daily/<TICKER>.parquet`)

`Date` (datetime64), `Open`, `High`, `Low`, `Close`, `Volume`. Nasdaq serves
these as strings with `$` and thousands separators; they are converted to floats
and nothing else is changed.

Prices are split-adjusted but **not** dividend-adjusted, so they cross-check
Yahoo's `Close`, not its `Adj Close`.

## Also here

`nasdaqtraded.txt` - Nasdaq's traded-symbol directory (994 KB), pipe-delimited,
with an `ETF` flag column that independently corroborates the ticker-reuse
screen of need #1.

## Comparison with need #1

Run `tools/e1_0_data/compare_sources.py` -> `_manifests/source_agreement.csv`.
Compare on **returns**, not levels: the two providers apply splits retroactively
at different times, so levels can differ by a constant factor while describing
the same security. Returns are invariant to that.

The comparison found `GP` - an ordinary Nasdaq-listed EQUITY with no metadata
anomaly whose returns did not match Yahoo's, because Yahoo serves GreenPower
Motor under the ticker the S&P 500 knew as Georgia-Pacific. That led to the
start-date reuse test described in the need #1 README.

## Sources refused (not worked around)

| source | why |
|---|---|
| Stooq | `robots.txt` is `User-agent: *` -> `Disallow: /` (only Googlebot and Bingbot allowed); also serves a JavaScript proof-of-work challenge to scripts |
| Tiingo, EODHD, Finnhub, Polygon, Marketstack | reachable, but all require an account and an API key |

## Files

%s
""" % (TODAY, len(xlog), len(xok), listing(f, skip={"retrieval_log.csv", "nasdaqtraded.txt"})))

    write_index()
    return 0


def _yfver() -> str:
    try:
        import yfinance
        return yfinance.__version__
    except Exception:
        return "?"


if __name__ == "__main__":
    raise SystemExit(main())
