"""
v2.1 Phase 6 -- the final measurements on the frozen generator, each stage its own files (rule 14), every output under
Phase-6 names (the Phase-4 lesson: an earlier chain overwrote another phase's files).

    python -m tools.phase6.e6_after_state --stages checklist,audit,holdout,hashes,freeze [--workers 24] [--seeds 500]

  checklist  the Section-9 checklist at the REGISTERED n (PREREG_PHASE_6.md 5.3: 500 seeds per scenario, SCL design,
             seeds from 40000, T = 200) under the v2 criteria (A, `run_checklist`, unchanged) AND the reference criteria
             (B and C, `run_checklist_reference`), with E6.8's rows and item 9's re-stated rule
             -> e6_after_checklist.{md,csv} (A), e6_after_checklist_reference.{md,csv,_items.csv} (B/C)
             plus T in {800, 2000} descriptive rows for items 4 and 9 at 100 flat seeds -> e6_after_checklist_long.{json,md}
  audit      evaluation.leakage_audit.run_audit on the 1,600-path SEP panel, level-free control, no subsampling, n/m as
             cap + indicator, gates="derived" (the derived L1/L2/L2b verdicts read from the criteria file)
             -> e6_after/audit_after_derived.{md,pkl,_L1.csv,_L2.csv,_L4.csv,_checklist_rows.csv}
  holdout    the held-out-scenario split (weakness 67) on the same panel -> e6_after/holdout.{csv,md}
  hashes     the 95-configuration path hashes -> path_hashes_phase6_after.json, compared with the Phase-5 fixture
             (nothing in Phase 6 changes the generator: the comparison must be empty)
  freeze     the manifest rewrite (a logged decision)

The panel must exist (`_panels/sep_phase5_after.pkl`, regenerated by tools.phase5.e5_after_state --stages panel on a
machine that has reproduced the reference rows); the criteria file must carry the gates for the audit's derived verdicts.
"""
from __future__ import annotations

import argparse
import json
import os
import pickle
import subprocess
import sys
import time

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)
os.environ.setdefault("OMP_NUM_THREADS", "2")
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:  # pragma: no cover
    pass

from tools.phase5.common import GEN, PANELS, encode_nm, pin_state  # noqa: E402

OUT = os.path.join(GEN, "e6_after")
PY = sys.executable
SCL_SEED0 = 40000
REF_WINDOWS = os.path.join(GEN, "e6_1", "windows.csv")


def _paths_parallel(n_seeds, T, seed0, workers):
    """checklist_paths' design built with a process pool (the serial builder is the dominant cost at 500 seeds)."""
    from concurrent.futures import ProcessPoolExecutor
    from tools.phase6.e6_after_state import _one_path  # module-level for spawn
    jobs = []
    for s in range(seed0, seed0 + n_seeds):
        jobs += [("flat", s, {}, T), ("bull_trap", s, {}, T), ("sustained_bull", s, {}, T)]
        jobs += [("crash", s, {"crash_discount": d}, T) for d in (0.55, 0.70, 0.85)]
    for s in range(seed0, seed0 + n_seeds):
        sc = ("crash", "bull_trap")[s % 2]
        jobs += [(sc, 1000 + s, {"ordering": "event_first"}, T), (sc, 2000 + s, {"ordering": "setup_first"}, T), ("flat", 3000 + s, {}, T)]
    with ProcessPoolExecutor(max_workers=workers) as ex:
        res = list(ex.map(_one_path, jobs, chunksize=8))
    out = {"flat": [], "bull_trap": [], "crash": [], "sustained_bull": [], "mixed": [], "flat_T800": []}
    n_main = 6 * n_seeds
    for (sc, s, kw, _), p in zip(jobs[:n_main], res[:n_main]):
        out[sc].append(p)
    for p in res[n_main:]:
        out["mixed"].append(p)
    return out


def _one_path(args):
    import warnings
    warnings.filterwarnings("ignore")
    os.environ.setdefault("OMP_NUM_THREADS", "1")
    from envs.synthetic_market import SyntheticMarketEnv, _path_data
    sc, s, kw, T = args
    return _path_data(SyntheticMarketEnv(sc, T, s, **kw))


def checklist(n_seeds, workers, n_boot=500):
    from evaluation.stylized_facts import run_checklist, to_markdown, run_checklist_reference, to_markdown_reference, path_reference_stats
    from evaluation import criteria as CR
    assert CR.PRESENT, "phase6_criteria.json absent"
    t0 = time.time()
    paths = _paths_parallel(n_seeds, 200, SCL_SEED0, workers)
    # the long flat paths for items 4 and 9 (descriptive), 20 seeds as the v2 design, from the same seed block
    from concurrent.futures import ProcessPoolExecutor
    with ProcessPoolExecutor(max_workers=workers) as ex:
        paths["flat_T800"] = list(ex.map(_one_path, [("flat", s, {}, 800) for s in range(SCL_SEED0, SCL_SEED0 + min(n_seeds, 20))]))
    print(f"paths built: {sum(len(v) for v in paths.values())} in {time.time() - t0:.0f} s", flush=True)
    # A: the v2 checklist, unchanged
    df = run_checklist(paths)
    out = os.path.join(GEN, "e6_after_checklist.md")
    pre = (f"Generator v2.1 after Phase 5 (frozen; Phase 6 changes no generator file); {n_seeds} seeds per scenario (crash: per delta), "
           f"T = 200, seeds from {SCL_SEED0} (SCL); v2 criteria (REG-14 A, `run_checklist` unchanged). Items 14 and 16 come from the "
           "leakage audit under the derived gates (e6_after/); 18 and 19 are unit tests.")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(to_markdown(df, "Section 9 validation checklist, standard checklist panel (Phase 6 after), v2 criteria", pre))
    df.to_csv(out.replace(".md", ".csv"), index=False)
    print(df[["item", "property", "pass"]].to_string(index=False), flush=True)
    # B and C: the reference criteria
    doc = CR.load()
    ref = pd.read_csv(REF_WINDOWS)
    t1 = time.time()
    gen_stats = path_reference_stats(paths)
    gen_stats.to_csv(os.path.join(GEN, "e6_after_checklist_reference_paths.csv"), index=False)
    res = run_checklist_reference(paths, doc, ref, n_boot=n_boot, gen_stats=gen_stats)
    out_r = os.path.join(GEN, "e6_after_checklist_reference.md")
    pre_r = (f"The same {n_seeds}-seed SCL paths under the reference criteria (REG-14 B and C; PREREG_PHASE_6.md section 5), "
             f"reference `e6_1/windows.csv` ({len(ref):,} windows); B is decisive only at n_gen >= {doc['criterion_B']['value'].get('n_min_size')}.")
    with open(out_r, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(to_markdown_reference(res, "Section 9 checklist under the reference criteria (Phase 6 after)", v2_df=df, preamble=pre_r))
    res["per_statistic"].to_csv(out_r.replace(".md", ".csv"), index=False)
    res["per_item"].to_csv(out_r.replace(".md", "_items.csv"), index=False)
    res["extra"].to_csv(out_r.replace(".md", "_extra.csv"), index=False)
    print(res["per_item"].to_string(index=False), flush=True)
    print(f"reference checklist: {time.time() - t1:.0f} s", flush=True)
    # the long horizons, descriptive
    from evaluation.stylized_facts import acf
    long = {}
    for T in (800, 2000):
        with ProcessPoolExecutor(max_workers=workers) as ex:
            lp = list(ex.map(_one_path, [("flat", s, {}, T) for s in range(SCL_SEED0, SCL_SEED0 + 100)]))
        a1 = [acf(p.df["x"].to_numpy(float), 1) for p in lp]
        hl = [(-np.log(2) / np.log(a)) if 0 < a < 1 else np.inf for a in a1]
        sd = [float(np.std(p.df["x"].to_numpy(float))) for p in lp]
        dec = {L: float(np.median([acf(np.abs(p.df["r"].dropna().to_numpy(float)), L) for p in lp])) for L in (1, 5, 10, 20, 50)}
        long[str(T)] = {"n": len(lp), "acf1_x_median": float(np.median(a1)), "half_life_median": float(np.median(hl)),
                        "sd_x_median": float(np.median(sd)), "acf_absr_median_by_lag": dec}
        print(f"T = {T}: ACF(1) of x {long[str(T)]['acf1_x_median']:.4f}, half-life {long[str(T)]['half_life_median']:.1f} d, sd(x) {long[str(T)]['sd_x_median']:.4f}", flush=True)
    json.dump({"what": "items 4 and 9 at T in {800, 2000}, 100 flat seeds, DESCRIPTIVE (never the pass criterion for a T = 200 property)",
               "seed0": SCL_SEED0, "by_T": long}, open(os.path.join(GEN, "e6_after_checklist_long.json"), "w", encoding="utf-8"), indent=1)
    print(f"checklist stage: {time.time() - t0:.0f} s", flush=True)


def checklist_reference_cached(n_seeds, n_boot=500):
    """Re-evaluate B and C from the cached per-path statistics and the cached E6.8 / item-9 rows (no path rebuild):
    used when the criteria file's `items` block is corrected after the checklist ran (the per-statistic population
    overrides and item 4's descriptive flag, PREREG 5.1)."""
    from evaluation.stylized_facts import run_checklist_reference, to_markdown_reference
    from evaluation import criteria as CR
    doc = CR.load()
    ref = pd.read_csv(REF_WINDOWS)
    g = pd.read_csv(os.path.join(GEN, "e6_after_checklist_reference_paths.csv"))
    extra_p = os.path.join(GEN, "e6_after_checklist_reference_extra.csv")
    extra = pd.read_csv(extra_p) if os.path.exists(extra_p) else None
    df = pd.read_csv(os.path.join(GEN, "e6_after_checklist.csv"))
    paths_stub = {sc: [None] * int((g["scenario"] == sc).sum()) for sc in g["scenario"].unique()}
    t0 = time.time()
    res = run_checklist_reference(paths_stub, doc, ref, n_boot=n_boot, gen_stats=g, extra=extra)
    out_r = os.path.join(GEN, "e6_after_checklist_reference.md")
    pre_r = (f"The same {n_seeds}-seed SCL paths under the reference criteria (REG-14 B and C; PREREG_PHASE_6.md section 5), "
             f"reference `e6_1/windows.csv` ({len(ref):,} windows); B is decisive only at n_gen >= {doc['criterion_B']['value'].get('n_min_size')}. "
             "Re-evaluated from the cached per-path statistics after the criteria file's items block was corrected (per-statistic "
             "population overrides; item 4 descriptive).")
    with open(out_r, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(to_markdown_reference(res, "Section 9 checklist under the reference criteria (Phase 6 after)", v2_df=df, preamble=pre_r))
    res["per_statistic"].to_csv(out_r.replace(".md", ".csv"), index=False)
    res["per_item"].to_csv(out_r.replace(".md", "_items.csv"), index=False)
    print(res["per_item"].to_string(index=False)); print(f"reference checklist (cached): {time.time() - t0:.0f} s")


def audit(holdout=False):
    from evaluation.leakage_audit import run_audit, to_markdown, checklist_rows
    from agent.render import rendered_market_fields
    os.makedirs(OUT, exist_ok=True)
    p = os.path.join(PANELS, "sep_phase5_after.pkl")
    pan = encode_nm(pd.read_pickle(p))
    shown = [f for f in rendered_market_fields("v2") if f in pan.columns] + (["reported_PE_nm"] if "reported_PE_nm" in pan else [])
    t0 = time.time()
    res = run_audit(pan, shown, max_rows=None, control="level_free", gates="derived", holdout_scenario=holdout)
    out = os.path.join(OUT, "audit_after_derived.md")
    with open(out.replace(".md", ".pkl"), "wb") as fh:
        pickle.dump(res, fh)
    res["L1"].to_csv(out.replace(".md", "_L1.csv"), index=False)
    res["L2"].to_csv(out.replace(".md", "_L2.csv"), index=False)
    res["L4"].to_csv(out.replace(".md", "_L4.csv"), index=False)
    pd.DataFrame(checklist_rows(res)).to_csv(out.replace(".md", "_checklist_rows.csv"), index=False)
    d = res["derived"]
    L = [to_markdown(res, f"Section 5 audit on the frozen generator (Phase 6; stored panel sep_phase5_after.pkl, {res['n_paths']} paths, "
                          f"T=200; 'n/m' as cap + indicator; derived gates)"), "",
         "## Derived gates (PREREG_PHASE_6.md sections 6-8)", "",
         f"L1: ceiling {d['L1'].get('margin_5pct', float('nan')):.4f} on the within-5 % share -> {'PASS' if d['L1'].get('pass') else 'FAIL'}; "
         f"price itself {float(res['L1'].loc[res['L1']['candidate'].str.contains('price itself'), 'within_5pct'].iloc[0]):.4f}.", ""]
    for name in ("l2_all", "l2_calm", "l2b"):
        g = d.get(name, {})
        if "error" in g:
            L.append(f"- {name}: {g['error']}")
        else:
            L.append(f"- {name}: measured {g.get('measured_selectivity', float('nan')):+.4f}, null median {g.get('null_median', float('nan')):+.4f}, "
                     f"p95 {g.get('null_p95', float('nan')):+.4f}, margin {g.get('margin', float('nan')):+.4f} -> {'PASS' if g.get('pass') else 'FAIL'}"
                     + (f"; the audit's own L2b selectivity {g.get('audit_selectivity', float('nan')):+.4f} -> {'PASS' if g.get('pass_audit_statistic') else 'FAIL'}" if name == "l2b" else "")
                     + f"; centred margin {g.get('centred_margin', float('nan')):+.4f} -> {'PASS' if g.get('pass_centred') else 'FAIL'}")
    L.append(f"\naudit GBT all-rows selectivity (the audit's own construction): {d.get('audit_gbt_selectivity_all', float('nan')):+.4f}")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    if holdout and "L2_holdout" in res:
        res["L2_holdout"].to_csv(os.path.join(OUT, "holdout.csv"), index=False)
    print(json.dumps({k: v for k, v in d.items() if k != "L1"}, indent=1, default=str)); print(f"audit: {time.time() - t0:.0f} s -> {out}")


def holdout():
    from evaluation.leakage_audit import l2_holdout_scenario
    from agent.render import rendered_market_fields
    os.makedirs(OUT, exist_ok=True)
    pan = encode_nm(pd.read_pickle(os.path.join(PANELS, "sep_phase5_after.pkl")))
    shown = [f for f in rendered_market_fields("v2") if f in pan.columns] + (["reported_PE_nm"] if "reported_PE_nm" in pan else [])
    t0 = time.time()
    df = l2_holdout_scenario(pan, [k for k in shown if k in pan.columns], control="level_free")
    df.to_csv(os.path.join(OUT, "holdout.csv"), index=False)
    L = ["# Held-out-scenario split (weakness 67): train on three scenarios, score the fourth", "",
         "| held out | feature set | model | population | n rows | R2(x) [CI] |", "|---|---|---|---|---|---|"]
    for _, r in df.iterrows():
        L.append(f"| {r['held_out']} | {r['feature_set']} | {r['model']} | {r['population']} | {r['n_rows']} | {r['R2']:+.4f} [{r['R2_lo']:+.4f}, {r['R2_hi']:+.4f}] |")
    with open(os.path.join(OUT, "holdout.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    print("\n".join(L)); print(f"holdout: {time.time() - t0:.0f} s")


def reattach():
    """Re-read the derived gates from the criteria file into the stored audit (no refit): used when the gates block is
    rewritten after the audit ran (the addendum's extra null draws)."""
    from evaluation.leakage_audit import derived_verdicts, checklist_rows
    p = os.path.join(OUT, "audit_after_derived.pkl")
    with open(p, "rb") as fh:
        res = pickle.load(fh)
    res["gates"] = "derived"; res["derived"] = derived_verdicts(res)
    with open(p, "wb") as fh:
        pickle.dump(res, fh)
    pd.DataFrame(checklist_rows(res)).to_csv(p.replace(".pkl", "_checklist_rows.csv"), index=False)
    d = res["derived"]
    md = os.path.join(OUT, "audit_after_derived.md")
    txt = open(md, encoding="utf-8").read()
    head = txt.split("## Derived gates")[0]
    L = [head.rstrip(), "", "## Derived gates (PREREG_PHASE_6.md sections 6-8; re-attached from the criteria file)", "",
         f"L1: ceiling {d['L1'].get('margin_5pct', float('nan')):.4f} on the within-5 % share -> {'PASS' if d['L1'].get('pass') else 'FAIL'}.", ""]
    for name in ("l2_all", "l2_calm", "l2b"):
        g = d.get(name, {})
        if "error" in g:
            L.append(f"- {name}: {g['error']}")
        else:
            L.append(f"- {name}: measured {g.get('measured_selectivity', float('nan')):+.4f}, null median {g.get('null_median', float('nan')):+.4f}, "
                     f"p95 {g.get('null_p95', float('nan')):+.4f} ({g.get('null_n_draws')} draws), margin {g.get('margin', float('nan')):+.4f} -> "
                     f"{'PASS' if g.get('pass') else 'FAIL'}" + (f"; the audit's own L2b selectivity {g.get('audit_selectivity', float('nan')):+.4f} -> "
                     f"{'PASS' if g.get('pass_audit_statistic') else 'FAIL'}" if name == "l2b" else "") +
                     f"; centred margin {g.get('centred_margin', float('nan')):+.4f} -> {'PASS' if g.get('pass_centred') else 'FAIL'}")
    L.append(f"\naudit GBT all-rows selectivity (the audit's own construction): {d.get('audit_gbt_selectivity_all', float('nan')):+.4f}")
    with open(md, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    print(json.dumps({k: v for k, v in d.items() if k != "L1"}, indent=1, default=str))


def hashes():
    from tools.path_hashes import build, compare
    out = os.path.join(GEN, "path_hashes_phase6_after.json")
    build(out)
    before = os.path.join(GEN, "path_hashes_phase5_after.json")
    r = compare(before, out)
    json.dump({k: (v if not isinstance(v, list) else v[:50]) for k, v in r.items()},
              open(os.path.join(GEN, "path_hashes_phase6_compare.json"), "w", encoding="utf-8"), indent=1, default=str)
    print("changes vs the Phase-5 fixture:", {k: (len(v) if isinstance(v, list) else v) for k, v in r.items()})


def freeze():
    subprocess.run([PY, "-m", "tools.freeze_manifest", "--write", "--label", "v2.1 Phase 6 freeze"], cwd=ROOT, check=False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stages", default="checklist,audit,holdout,hashes,freeze")
    ap.add_argument("--workers", type=int, default=3)
    ap.add_argument("--seeds", type=int, default=500)
    a = ap.parse_args()
    pin_state()
    fns = {"checklist": lambda: checklist(a.seeds, a.workers), "checklist_reference": lambda: checklist_reference_cached(a.seeds),
           "audit": lambda: audit(False), "holdout": holdout, "reattach": reattach, "hashes": hashes, "freeze": freeze}
    for s in a.stages.split(","):
        t0 = time.time(); print(f"[after_state] {s} ...", flush=True)
        fns[s.strip()]()
        print(f"[after_state] {s}: {time.time() - t0:.0f} s", flush=True)


if __name__ == "__main__":
    main()
