"""
E2.5 (PREREG_PHASE_2.md section 7): the half-life estimator lookup table.

Pure AR(1) x_{t+1} = rho x_t + e_t, rho = 2^(-1/h), Gaussian e scaled to unit stationary variance (no GARCH, no
V, no events -- the table is a property of the ESTIMATOR, not of the engine).  True half-life
h in {30, 60, 120, 150, 250, 500, 600} d x T in {200, 800, 2000, 5000}, 200 seeds per cell (seeds HL 120001+).

Per cell: the distribution of (i) the naive ACF(1) half-life -ln2 / ln(rho_hat_OLS) and (ii) the Andrews (1993)
MEDIAN-UNBIASED estimate, whose median function m_T(rho) is regenerated by simulation at each T (20,000
replicates per rho grid point) rather than read from a table fitted at another T.  Reported: median, P25/P75, a
95 % interval on the median (1,000-resample bootstrap over seeds), and the share of cells whose naive estimate
clears the plan's 60-day floor.

Also reported at the live engine's half-life, on the ADOPTED engine (E2.4): sd of x within 200 days and the
number of oracle target switches per run -- "what the agent experiences".

    python -m tools.phase2.e2_5_hl_table [--n-seeds 200] [--hs 30,60,...] [--Ts 200,800,2000,5000]
Outputs: docs/env_v2/generated/v2_1/e2_5/hl_table.json, hl_table.md, andrews_median_T<T>.npz
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)
os.environ.setdefault("OMP_NUM_THREADS", "2")

OUT = os.path.join(ROOT, "docs", "env_v2", "generated", "v2_1", "e2_5")
SEED_HL = 120001
HS = (30, 60, 120, 150, 250, 500, 600)
TS = (200, 800, 2000, 5000)
RHO_GRID = np.concatenate([np.linspace(0.0, 0.9, 46), np.linspace(0.902, 0.9999, 120)])
N_REP_MEDIAN = 20000
# The median function is expensive in T x n_rep.  The OLS bias is O(1/T), so at long T it is small and the
# function is close to the identity: the replicate count is reduced with T (and the reduced counts are stated in
# the output JSON) so that the whole table costs minutes rather than hours.  The grid is unchanged.
N_REP_BY_T = {200: 20000, 800: 20000, 2000: 8000, 5000: 4000}
HL_GRID_TOP = -math.log(2.0) / math.log(0.9999)   # 6931 d: the half-life at the top of RHO_GRID; the
# median-unbiased estimate is CENSORED there, and the censored share is reported with every cell


def ols_rho(y: np.ndarray) -> np.ndarray:
    a, b = y[:-1], y[1:]
    a = a - a.mean(axis=0)
    b = b - b.mean(axis=0)
    return (a * b).sum(axis=0) / np.maximum((a * a).sum(axis=0), 1e-300)


def ar1(h: float, T: int, n: int, seed: int) -> np.ndarray:
    rho = 2.0 ** (-1.0 / h)
    rng = np.random.default_rng(seed)
    e = rng.standard_normal((T, n)) * math.sqrt(1.0 - rho ** 2)
    x = np.empty((T, n))
    x[0] = rng.standard_normal(n)
    for t in range(1, T):
        x[t] = rho * x[t - 1] + e[t]
    return x


def median_function(T: int, seed: int = 654321, n_rep: int = None) -> np.ndarray:
    """m_T(rho) = median of the OLS rho-hat with intercept, by simulation (Andrews 1993's exact median function,
    regenerated rather than interpolated from another T)."""
    path = os.path.join(OUT, f"andrews_median_T{T}.npz")
    if os.path.exists(path):
        return np.load(path)["median"]
    n_rep = int(n_rep or N_REP_BY_T.get(T, N_REP_MEDIAN))
    rng = np.random.default_rng(seed + T)
    med = np.empty(len(RHO_GRID))
    chunk = 4000
    for j, rho in enumerate(RHO_GRID):
        vals = []
        for c in range(0, n_rep, chunk):
            n = min(chunk, n_rep - c)
            e = rng.standard_normal((T, n))
            y = np.empty((T, n))
            y[0] = e[0] / math.sqrt(max(1 - rho ** 2, 1e-9))
            for t in range(1, T):
                y[t] = rho * y[t - 1] + e[t]
            vals.append(ols_rho(y))
        med[j] = float(np.median(np.concatenate(vals)))
    os.makedirs(OUT, exist_ok=True)
    np.savez(path, rho=RHO_GRID, median=med, T=T, n_rep=n_rep)
    return med


def median_unbiased(rho_hat: np.ndarray, med: np.ndarray) -> np.ndarray:
    return np.interp(rho_hat, med, RHO_GRID, left=RHO_GRID[0], right=RHO_GRID[-1])


def hl(rho: np.ndarray) -> np.ndarray:
    r = np.clip(rho, 1e-9, 1 - 1e-12)
    return np.where(rho > 0, -math.log(2.0) / np.log(r), np.nan)


def boot_median_ci(a: np.ndarray, n_boot: int = 1000, seed: int = 11) -> list:
    rng = np.random.default_rng(seed)
    a = a[np.isfinite(a)]
    if len(a) < 3:
        return [float("nan"), float("nan")]
    b = np.array([np.median(a[rng.integers(0, len(a), len(a))]) for _ in range(n_boot)])
    return [float(np.percentile(b, 2.5)), float(np.percentile(b, 97.5))]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-seeds", type=int, default=200)
    ap.add_argument("--hs", default=",".join(str(h) for h in HS))
    ap.add_argument("--Ts", default=",".join(str(t) for t in TS))
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    hs = [int(v) for v in a.hs.split(",")]
    Ts = [int(v) for v in a.Ts.split(",")]
    t0 = time.time()
    meds = {T: median_function(T) for T in Ts}
    print(f"Andrews median functions regenerated ({ {T: N_REP_BY_T.get(T, N_REP_MEDIAN) for T in Ts} } reps per rho, "
          f"{len(RHO_GRID)} grid points) in {time.time() - t0:.0f} s", flush=True)
    res = {"design": {"hs": hs, "Ts": Ts, "n_seeds": a.n_seeds, "seed0": SEED_HL,
                      "n_rep_median": {str(T): int(N_REP_BY_T.get(T, N_REP_MEDIAN)) for T in Ts},
                      "rho_grid": [float(RHO_GRID[0]), float(RHO_GRID[-1]), len(RHO_GRID)],
                      "model": "pure AR(1), Gaussian, unit stationary variance"}, "cells": {}}
    for h in hs:
        for T in Ts:
            x = ar1(h, T, a.n_seeds, SEED_HL + 977 * hs.index(h) + T)
            rho_hat = ols_rho(x)
            hl_naive = hl(rho_hat)
            hl_mu = hl(median_unbiased(rho_hat, meds[T]))
            cell = {"h_true": h, "T": T, "n": a.n_seeds}
            for nm, v in (("naive", hl_naive), ("median_unbiased", hl_mu)):
                f = v[np.isfinite(v)]
                cell[nm] = {"median": float(np.median(f)) if len(f) else float("nan"),
                            "p25": float(np.percentile(f, 25)) if len(f) else float("nan"),
                            "p75": float(np.percentile(f, 75)) if len(f) else float("nan"),
                            "ci95_median": boot_median_ci(v),
                            "n_finite": int(len(f)),
                            "share_ge_60d": float(np.mean(v >= 60.0)),
                            "share_at_grid_top": float(np.mean(v >= 0.999 * HL_GRID_TOP)),
                            "median_rel_error": float(np.median(f) / h - 1.0) if len(f) else float("nan")}
            res["cells"][f"h{h}|T{T}"] = cell
            print(f"  h={h:4d} T={T:5d}: naive {cell['naive']['median']:7.1f} "
                  f"[{cell['naive']['p25']:.1f}, {cell['naive']['p75']:.1f}]  "
                  f"median-unbiased {cell['median_unbiased']['median']:7.1f} "
                  f"[{cell['median_unbiased']['p25']:.1f}, {cell['median_unbiased']['p75']:.1f}]", flush=True)
    res["seconds"] = round(time.time() - t0)
    with open(os.path.join(OUT, "hl_table.json"), "w", encoding="utf-8") as fh:
        json.dump(res, fh, indent=1)
    L = ["# E2.5 half-life estimator lookup table (PREREG_PHASE_2.md section 7)", "",
         f"Pure AR(1) with Gaussian innovations and unit stationary variance; {a.n_seeds} seeds per cell "
         f"(seeds from {SEED_HL}).  `naive` = -ln2 / ln(rho_hat_OLS); `median-unbiased` = the same after "
         f"inverting Andrews' (1993) exact median function m_T(rho), regenerated by simulation at each T "
         f"({res['design']['n_rep_median']} replicates per rho grid point).  Cells are `median [P25, P75]`; the interval on the "
         "median is a 1,000-resample bootstrap over seeds.", "",
         "| true h | " + " | ".join(f"T = {T}" for T in Ts) + " |", "|---|" + "---|" * len(Ts)]
    for est in ("naive", "median_unbiased"):
        L.append(f"| **{est}** |" + " |" * len(Ts))
        for h in hs:
            row = [f"| {h} "]
            for T in Ts:
                c = res["cells"][f"h{h}|T{T}"][est]
                row.append(f"| {c['median']:.1f} [{c['p25']:.1f}, {c['p75']:.1f}] "
                           f"(CI {c['ci95_median'][0]:.1f}-{c['ci95_median'][1]:.1f}) ")
            L.append("".join(row) + "|")
    L += ["", "Share of paths whose **median-unbiased** estimate is CENSORED at the top of the rho grid "
              f"(rho = 0.9999, i.e. a half-life of {HL_GRID_TOP:.0f} d) -- where this is non-trivial the cell's "
              "median and P75 are not estimates of h but of the ceiling:", "",
          "| true h | " + " | ".join(f"T = {T}" for T in Ts) + " |", "|---|" + "---|" * len(Ts)]
    for h in hs:
        L.append(f"| {h} | " + " | ".join(f"{res['cells'][f'h{h}|T{T}']['median_unbiased']['share_at_grid_top']:.2f}"
                                          for T in Ts) + " |")
    L += ["", "Share of paths whose **naive** estimate clears the plan's 60-day floor:", "",
          "| true h | " + " | ".join(f"T = {T}" for T in Ts) + " |", "|---|" + "---|" * len(Ts)]
    for h in hs:
        L.append(f"| {h} | " + " | ".join(f"{res['cells'][f'h{h}|T{T}']['naive']['share_ge_60d']:.2f}" for T in Ts) + " |")
    with open(os.path.join(OUT, "hl_table.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    print("written", OUT, f"{time.time() - t0:.0f} s")


if __name__ == "__main__":
    main()
